#!/usr/bin/python3

SAMPLE_PNG_FULL_FILENAME = 'sample.png'
SAMPLE_PNG_FILE_PATH = './'
SAMPLE_PNG_FULL_FILE_PATH = SAMPLE_PNG_FILE_PATH + SAMPLE_PNG_FULL_FILENAME

RESULTS_FULL_FILENAME = 'results.dupeguru'
RESULTS_FILE_PATH = './'
RESULTS_FULL_FILE_PATH = RESULTS_FILE_PATH + RESULTS_FULL_FILENAME
