#!/usr/bin/python3
'''defines module'''

SAMPLE_PNG_FULL_FILENAME = 'sample.png'
SAMPLE_PNG_FILE_PATH = './'
SAMPLE_PNG_FULL_FILE_PATH = SAMPLE_PNG_FILE_PATH + SAMPLE_PNG_FULL_FILENAME

RESULTS_FULL_FILENAME = 'results.dupeguru'
RESULTS_FILE_PATH = './'
DEFAULT_RESULTS_FULL_FILE_PATH = RESULTS_FILE_PATH + RESULTS_FULL_FILENAME

# Error messages
COULD_NOT_FIND_RESULTS_FILE = "Could not find 'results.dupeguru' file"
